### PR TITLE
reduce allocations in generic_fft

### PR DESCRIPTION
**Pull request by jishnub**
On main
```julia
julia> v = rand(10025);

julia> @btime GenericFFT.generic_fft($v);
  7.006 ms (71 allocations: 10.17 MiB)
```
This PR
```julia
julia> @btime GenericFFT.generic_fft($v);
  6.467 ms (41 allocations: 6.15 MiB)
```

### CODE REVIEW

**Comment by jishnub** [comment]
I've updated the name of the function to `interlace_complex`

**Comment by jishnub** [comment]
Gentle bump @milankl

**Comment by milankl** [comment]
@jishnub I've added an `@inbounds` and also tests

**Comment by milankl** [comment]
I've added tests with `conjfn in (identity,-)`, otherwise I don't understand why codecov keeps failing?

**Comment by jishnub** [comment]
`interlace(a::AbstractVector{S},b::AbstractVector{V}) where {S<:Number,V<:Number}` appears not to be tested anymore, as we are using the new complex methods. Do we need to retain this, assuming this is treated as internal?

**Comment by milankl** [comment]
Good point, I'd personally comment it out if it's currently not used, just with a remark that it's an older version. I find that more verbose than either just deleting it or keeping it in, suggesting it is actually used

**Comment by dlfivefifty** [comment]
This should have been a breaking change as `interlace` was used in FastTransforms.jl. I'll uncomment it out and tag a new patch version.

**Pull request merged**
