### PR TITLE
plan_(b)rfft types as in FFTW

### PR DESCRIPTION
**Pull request by milankl**
This should address #14

### CODE REVIEW

**Review by daanhb — APPROVED** [review]

**Comment by daanhb** [comment]
We have to remember to decide on a release number, I think this should be 0.2.

**Comment by milankl** [comment]
Before we tag it as v0.2 I thought about getting the sizes into the plans too as raised in #10 ?

**Comment by daanhb** [comment]
Yes, sure. I'll merge this and we can change the version number later.

**Comment by daanhb** [comment]
(I forgot you could merge yourself)

**Pull request merged**
